version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.4.2
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: prova_infuse
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  api:
    container_name: api
    build: .
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/prova_infuse
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    volumes:
      - ../:/spring-boot-api
    networks:
      - app-network
    depends_on:
      - mysql

volumes:
  mysql-data:
networks:
  app-network:
    driver: bridge
